using System;
using System.Collections.Generic;
using TerrariumDays.Core;
using TerrariumDays.Gameplay;
using UnityEngine;

namespace TerrariumDays.UI
{
    /// <summary>
    /// The gecko animation frames and effect sprites under Resources/ (generated by
    /// tools/sprites/gecko_sprites.py), grouped per clip by their file-name prefix and ordered
    /// by index. Frames are recoloured to a morph's palette on first request and cached; the
    /// pre-shed look is derived at runtime from MorphAppearance.PreShed rather than loaded from
    /// a separate pre-rendered set.
    /// </summary>
    public sealed class PetSpriteLibrary
    {
        private readonly Dictionary<PetClip, Texture2D[]> frames;
        private readonly MorphPalette palette;
        private readonly Dictionary<(PetClip, int, bool), Texture2D> cache = new Dictionary<(PetClip, int, bool), Texture2D>();

        public PetSpriteLibrary(IEnumerable<Texture2D> geckoFrames, Texture2D heart, Texture2D zzz, MorphPalette palette = null)
            : this(Group(geckoFrames), heart, zzz, palette ?? MorphAppearance.Normal)
        {
        }

        private PetSpriteLibrary(Dictionary<PetClip, Texture2D[]> frames, Texture2D heart, Texture2D zzz, MorphPalette palette)
        {
            this.frames = frames;
            this.palette = palette;
            Heart = heart;
            Zzz = zzz;
        }

        /// <summary>A library with the same frames, recoloured to another morph's palette.</summary>
        public PetSpriteLibrary WithPalette(MorphPalette palette)
        {
            return new PetSpriteLibrary(frames, Heart, Zzz, palette);
        }

        private static Dictionary<PetClip, Texture2D[]> Group(IEnumerable<Texture2D> textures)
        {
            var frames = new Dictionary<PetClip, Texture2D[]>();
            var byClip = new Dictionary<PetClip, List<Texture2D>>();
            foreach (var texture in textures)
            {
                foreach (PetClip clip in Enum.GetValues(typeof(PetClip)))
                {
                    if (texture.name.StartsWith(PetAnimation.ResourcePrefix(clip) + "_", StringComparison.Ordinal))
                    {
                        if (!byClip.TryGetValue(clip, out var list))
                        {
                            byClip[clip] = list = new List<Texture2D>();
                        }

                        list.Add(texture);
                    }
                }
            }

            foreach (var pair in byClip)
            {
                pair.Value.Sort((a, b) => string.CompareOrdinal(a.name, b.name));
                frames[pair.Key] = pair.Value.ToArray();
            }

            return frames;
        }

        public Texture2D Heart { get; }

        public Texture2D Zzz { get; }

        public static PetSpriteLibrary LoadFromResources()
        {
            return new PetSpriteLibrary(
                Resources.LoadAll<Texture2D>("Gecko"),
                Resources.Load<Texture2D>("Effects/heart"),
                Resources.Load<Texture2D>("Effects/zzz"));
        }

        public int FrameCount(PetClip clip)
        {
            return frames.TryGetValue(clip, out var list) ? list.Length : 0;
        }

        /// <summary>The frame to show, falling back to idle if a clip has no frames.</summary>
        public Texture2D Frame(PetClip clip, int index, bool preShed)
        {
            var source = SourceFrame(clip, index);
            if (source == null)
            {
                return null;
            }

            if (palette.Key == MorphAppearance.Normal.Key && !preShed)
            {
                return source;
            }

            var key = (clip, index, preShed);
            if (!cache.TryGetValue(key, out var recoloured))
            {
                recoloured = MorphRecolor.Apply(source, palette, preShed);
                cache[key] = recoloured;
            }

            return recoloured;
        }

        /// <summary>The frame to show, falling back to idle if a clip has no frames.</summary>
        public Texture2D Frame(PetClip clip, int index)
        {
            return Frame(clip, index, false);
        }

        private Texture2D SourceFrame(PetClip clip, int index)
        {
            if (!frames.TryGetValue(clip, out var list) || list.Length == 0)
            {
                if (clip == PetClip.Idle)
                {
                    return null;
                }

                return SourceFrame(PetClip.Idle, index);
            }

            return list[Mathf.Clamp(index, 0, list.Length - 1)];
        }
    }
}
