using System;
using System.Collections.Generic;
using TerrariumDays.Gameplay;
using UnityEngine;

namespace TerrariumDays.UI
{
    /// <summary>
    /// The gecko animation frames and effect sprites under Resources/ (generated by
    /// tools/sprites/gecko_sprites.py): the normal set and a pale pre-shed set with the same
    /// poses. Frames are grouped per clip by their file-name prefix and ordered by index.
    /// </summary>
    public sealed class PetSpriteLibrary
    {
        private readonly Dictionary<PetClip, Texture2D[]> frames;
        private readonly Dictionary<PetClip, Texture2D[]> preShedFrames;

        public PetSpriteLibrary(IEnumerable<Texture2D> geckoFrames, Texture2D heart, Texture2D zzz,
            IEnumerable<Texture2D> preShedGeckoFrames = null)
        {
            Heart = heart;
            Zzz = zzz;
            frames = Group(geckoFrames);
            preShedFrames = preShedGeckoFrames != null ? Group(preShedGeckoFrames) : new Dictionary<PetClip, Texture2D[]>();
        }

        private static Dictionary<PetClip, Texture2D[]> Group(IEnumerable<Texture2D> textures)
        {
            var frames = new Dictionary<PetClip, Texture2D[]>();
            var byClip = new Dictionary<PetClip, List<Texture2D>>();
            foreach (var texture in textures)
            {
                foreach (PetClip clip in Enum.GetValues(typeof(PetClip)))
                {
                    if (texture.name.StartsWith(PetAnimation.ResourcePrefix(clip) + "_", StringComparison.Ordinal))
                    {
                        if (!byClip.TryGetValue(clip, out var list))
                        {
                            byClip[clip] = list = new List<Texture2D>();
                        }

                        list.Add(texture);
                    }
                }
            }

            foreach (var pair in byClip)
            {
                pair.Value.Sort((a, b) => string.CompareOrdinal(a.name, b.name));
                frames[pair.Key] = pair.Value.ToArray();
            }

            return frames;
        }

        public Texture2D Heart { get; }

        public Texture2D Zzz { get; }

        public static PetSpriteLibrary LoadFromResources()
        {
            return new PetSpriteLibrary(
                Resources.LoadAll<Texture2D>("Gecko"),
                Resources.Load<Texture2D>("Effects/heart"),
                Resources.Load<Texture2D>("Effects/zzz"),
                Resources.LoadAll<Texture2D>("GeckoPreShed"));
        }

        public int FrameCount(PetClip clip)
        {
            return frames.TryGetValue(clip, out var list) ? list.Length : 0;
        }

        /// <summary>The pale pre-shed version of a frame (falls back to the normal frame).</summary>
        public Texture2D Frame(PetClip clip, int index, bool preShed)
        {
            if (preShed && preShedFrames.TryGetValue(clip, out var list) && list.Length > 0)
            {
                return list[Mathf.Clamp(index, 0, list.Length - 1)];
            }

            return Frame(clip, index);
        }

        /// <summary>The frame to show, falling back to idle if a clip has no frames.</summary>
        public Texture2D Frame(PetClip clip, int index)
        {
            if (!frames.TryGetValue(clip, out var list) || list.Length == 0)
            {
                if (clip == PetClip.Idle)
                {
                    return null;
                }

                return Frame(PetClip.Idle, index);
            }

            return list[Mathf.Clamp(index, 0, list.Length - 1)];
        }
    }
}
